server:
  port: 8080

spring:
  datasource:
    username: mariakirnitskaya
    password:
    url: jdbc:postgresql://localhost:5432/search_engine
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect # Для уверенности

  liquibase:
    # Убедись, что путь начинается с classpath:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true

indexing-settings:
  sites:
    - url: https://www.svetlovka.ru
      name: Светловка
    - url: https://www.skillbox.ru
      name: Skillbox
    - url: http://radiomv.ru/
      name: RadioMV
    - url: https://dimonvideo.ru
      name: Dimonvideo.ru
    - url: https://www.lenta.ru
      name: Лента.ру
